/**
 * Encrypted at-rest storage for the data this app keeps about people.
 *
 * Invoify has no server and no account, so an address book, a draft and a pile
 * of saved invoices all live in the browser. That is the design, not an
 * oversight — but until now it meant names, postal addresses, emails and phone
 * numbers sat in the profile directory as readable JSON, where a shared
 * laptop, a filesystem backup, a synced profile or another OS account could
 * read them without ever visiting the site.
 *
 * WHAT THIS DEFENDS AGAINST, precisely, because "encrypted" on the web is
 * easily oversold:
 *
 *   yes  someone reading the browser profile off disk — stolen or shared
 *        machine, backup, profile sync, forensic recovery, another OS user
 *   no   cross-site scripting on this origin. A script running on the page
 *        holds the same key handle the app does and can simply call decrypt().
 *
 * There is no keyless way to beat the second one. Doing so needs a passphrase
 * the user supplies and the app never stores, which costs a prompt to reach
 * your own address book and loses the data outright if it is forgotten. That
 * is a product decision, not a default.
 *
 * The key is an AES-GCM 256 key generated by the browser with
 * `extractable: false`. Non-extractable is the whole point: `crypto.subtle`
 * hands out a usable handle but will never export the bytes, so the key cannot
 * be copied out of the origin — not by this code, and not by anything that
 * reads the IndexedDB file.
 *
 * Ciphertext lives in IndexedDB as raw bytes rather than base64 in
 * localStorage. That is not a style preference; it was measured. A draft
 * carrying an uploaded logo is about 1.9MB, and for that payload:
 *
 *   encrypt                     5.4ms   (promise-based, off the main thread)
 *   base64 encode             168.8ms   (synchronous, on the main thread)
 *   localStorage.setItem       17.5ms
 *   IndexedDB put, raw bytes   16.6ms
 *
 * Base64 was thirty times the cost of the encryption it existed to carry, all
 * of it blocking, on the same autosave path a previous round went to some
 * trouble to unblock. Dropping it also drops the 33% that base64 adds to every
 * stored byte, which matters when the browser's quota is the ceiling.
 */

const DB_NAME = "invoify-secure";
/** v2 added the values store; v1 held only the key. */
const DB_VERSION = 2;
const KEY_STORE = "keys";
const VALUE_STORE = "values";
const KEY_ID = "storage-key";

/** AES-GCM's standard nonce length. Fresh for every single write. */
const IV_BYTES = 12;

const hasCrypto = () =>
    typeof window !== "undefined" &&
    typeof window.crypto?.subtle?.encrypt === "function" &&
    typeof window.indexedDB !== "undefined";

function openDb(): Promise<IDBDatabase> {
    return new Promise((resolve, reject) => {
        const request = window.indexedDB.open(DB_NAME, DB_VERSION);
        request.onupgradeneeded = () => {
            const db = request.result;
            if (!db.objectStoreNames.contains(KEY_STORE)) {
                db.createObjectStore(KEY_STORE);
            }
            if (!db.objectStoreNames.contains(VALUE_STORE)) {
                db.createObjectStore(VALUE_STORE);
            }
        };
        request.onsuccess = () => resolve(request.result);
        request.onerror = () => reject(request.error);
    });
}

function idbGet<T>(
    db: IDBDatabase,
    store: string,
    id: string
): Promise<T | undefined> {
    return new Promise((resolve, reject) => {
        const request = db
            .transaction(store, "readonly")
            .objectStore(store)
            .get(id);
        request.onsuccess = () => resolve(request.result as T | undefined);
        request.onerror = () => reject(request.error);
    });
}

function idbPut(
    db: IDBDatabase,
    store: string,
    id: string,
    value: unknown
): Promise<void> {
    return new Promise((resolve, reject) => {
        const tx = db.transaction(store, "readwrite");
        tx.objectStore(store).put(value, id);
        tx.oncomplete = () => resolve();
        tx.onerror = () => reject(tx.error);
    });
}

function idbDelete(db: IDBDatabase, store: string, id: string): Promise<void> {
    return new Promise((resolve, reject) => {
        const tx = db.transaction(store, "readwrite");
        tx.objectStore(store).delete(id);
        tx.oncomplete = () => resolve();
        tx.onerror = () => reject(tx.error);
    });
}

/**
 * The origin's database and key, opened once and reused.
 *
 * Cached as a promise rather than a value so that concurrent callers — the
 * draft flush and both address books can easily race on first paint — share
 * one generation instead of each minting a key and the last writer winning,
 * which would leave the others' ciphertext undecryptable.
 */
let vaultPromise: Promise<{ db: IDBDatabase; key: CryptoKey } | null> | null =
    null;

function getVault(): Promise<{ db: IDBDatabase; key: CryptoKey } | null> {
    if (vaultPromise) return vaultPromise;

    vaultPromise = (async () => {
        if (!hasCrypto()) return null;
        try {
            const db = await openDb();

            const existing = await idbGet<CryptoKey>(db, KEY_STORE, KEY_ID);
            if (existing) return { db, key: existing };

            const key = await window.crypto.subtle.generateKey(
                { name: "AES-GCM", length: 256 },
                // Non-extractable. This is what stops the key being read back
                // out of IndexedDB by anything, including this module.
                false,
                ["encrypt", "decrypt"]
            );
            await idbPut(db, KEY_STORE, KEY_ID, key);
            return { db, key };
        } catch {
            /*
             * Private-browsing modes and hardened configurations can refuse
             * IndexedDB outright. Returning null degrades to "cannot persist"
             * rather than to "persist in the clear" — writing PII unencrypted
             * because the encryption was unavailable would defeat the point.
             */
            return null;
        }
    })();

    return vaultPromise;
}

/**
 * One queue per storage key, so operations on the same key run in call order.
 *
 * Without this they race, and the race is not theoretical: clearing the draft
 * for a new invoice and the debounced write of that new invoice both target
 * the same key, and the clear has to wait on the vault — which on a cold start
 * includes generating the key. The delete could therefore land after the write
 * and wipe the invoice that had just been created.
 *
 * Reads are queued too, so a read issued after a write sees that write rather
 * than whatever preceded it.
 */
const queues = new Map<string, Promise<unknown>>();

function enqueue<T>(storageKey: string, task: () => Promise<T>): Promise<T> {
    const previous = queues.get(storageKey) ?? Promise.resolve();
    // Swallow the predecessor's rejection: one failed write must not poison
    // every later operation on that key.
    const next = previous.then(task, task);
    queues.set(
        storageKey,
        next.catch(() => undefined)
    );
    return next;
}

/** Reads a value left in localStorage by a build from before this module. */
function readLegacy<T>(storageKey: string): T | null {
    try {
        const raw = window.localStorage.getItem(storageKey);
        if (!raw) return null;
        return JSON.parse(raw) as T;
    } catch {
        return null;
    }
}

/**
 * Reads and decrypts a value.
 *
 * Falls back to the plaintext localStorage entry an older build left behind,
 * then migrates it: the value is rewritten encrypted and the plaintext copy is
 * deleted. Leaving the old copy in place would encrypt nothing in practice,
 * since the readable version would still be sitting on disk beside it.
 */
export function readSecure<T>(storageKey: string): Promise<T | null> {
    if (typeof window === "undefined") return Promise.resolve(null);
    return enqueue(storageKey, () => readNow<T>(storageKey));
}

async function readNow<T>(storageKey: string): Promise<T | null> {
    const vault = await getVault();

    if (!vault) {
        // Cannot decrypt anything; the legacy copy is all there is.
        return readLegacy<T>(storageKey);
    }

    try {
        const stored = await idbGet<Uint8Array>(
            vault.db,
            VALUE_STORE,
            storageKey
        );

        if (!stored) {
            const legacy = readLegacy<T>(storageKey);
            if (legacy !== null) {
                /*
                 * Upgrade in place, inside this same queued task, so the
                 * migration cannot be overtaken by a write issued immediately
                 * after the read that triggered it.
                 */
                await writeNow(storageKey, legacy);
            }
            return legacy;
        }

        const bytes = new Uint8Array(stored);
        const plaintext = await window.crypto.subtle.decrypt(
            { name: "AES-GCM", iv: bytes.subarray(0, IV_BYTES) },
            vault.key,
            bytes.subarray(IV_BYTES)
        );

        return JSON.parse(new TextDecoder().decode(plaintext)) as T;
    } catch {
        /*
         * Wrong key or tampered ciphertext — AES-GCM authenticates, so a
         * modified payload fails here rather than decrypting to nonsense. The
         * realistic cause is the key record having been cleared while the
         * values survived, which no amount of retrying fixes.
         */
        return null;
    }
}

/**
 * Encrypts and stores a value. Resolves false if it could not be persisted.
 *
 * Callers treat a false the same way they already treated a quota error: the
 * address book and the draft are conveniences, and failing to write one must
 * never interrupt the invoice being edited.
 */
export function writeSecure(
    storageKey: string,
    value: unknown
): Promise<boolean> {
    if (typeof window === "undefined") return Promise.resolve(false);
    return enqueue(storageKey, () => writeNow(storageKey, value));
}

async function writeNow(storageKey: string, value: unknown): Promise<boolean> {
    const vault = await getVault();
    if (!vault) return false;

    try {
        const iv = window.crypto.getRandomValues(new Uint8Array(IV_BYTES));
        const ciphertext = await window.crypto.subtle.encrypt(
            { name: "AES-GCM", iv },
            vault.key,
            new TextEncoder().encode(JSON.stringify(value))
        );

        const payload = new Uint8Array(IV_BYTES + ciphertext.byteLength);
        payload.set(iv, 0);
        payload.set(new Uint8Array(ciphertext), IV_BYTES);

        await idbPut(vault.db, VALUE_STORE, storageKey, payload);

        // The plaintext predecessor, if there was one, is now redundant and is
        // the only readable copy left. Remove it.
        try {
            window.localStorage.removeItem(storageKey);
        } catch {
            // Storage disabled; nothing readable was written there anyway.
        }

        return true;
    } catch {
        // Quota exceeded, storage disabled, or crypto refused.
        return false;
    }
}

/** Deletes a value, including any plaintext copy from an older build. */
export function removeSecure(storageKey: string): Promise<void> {
    if (typeof window === "undefined") return Promise.resolve();
    return enqueue(storageKey, () => removeNow(storageKey));
}

async function removeNow(storageKey: string): Promise<void> {
    try {
        window.localStorage.removeItem(storageKey);
    } catch {
        // Nothing useful to do.
    }

    const vault = await getVault();
    if (!vault) return;
    try {
        await idbDelete(vault.db, VALUE_STORE, storageKey);
    } catch {
        // Same.
    }
}

/** Test seam: forget the cached handles so the next call re-opens them. */
export function __resetVaultCache(): void {
    vaultPromise = null;
    queues.clear();
}
